### ISSUE TITLE
Install all dependencies for project superbook2 (including dev) fails

### ISSUE THREAD

**Issue by wise-ksf** [DjangoPatternsBook/superbook2#8]
Hi Arun et. al. and thanks for your DjangoPatternsBook and code.

I have the book and would like to follow along with the code, but I think I found a bug because it's failing for me right at the starting line on two different computers using different python environments, so I don't think it's my environment that's causing the problem.

From the book section **Starting the project**:

First, clone the example project from GitHub:

`   $ git clone https://github.com/DjangoPatternsBook/superbook2.git`

Next, install `pipenv` system-wide [this is what I did, using brew on MacOS and using dnf on Fedora 32] or locally, but outside a `virtualenv` as recommended in `pipenv` installation documents. Alternatively, follow these commands [I did not do this]:

```
   $ pip install -U pip
   $ pip install pipenv

```
Now go to the project directory and install the dependencies:

```
   $ cd superbook2
   $ pipenv install --dev
```

This is where it fails for me with the message:

```
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.python.org/simple', 'Collecting markupsafe==1.0', '  Using cached MarkupSafe-1.0.tar.gz (14 kB)']
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '     command: /home/alpha/.local/share/virtualenvs/superbook2-HNnQDu9M/bin/python3 -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-5kl59pd3/markupsafe/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-5kl59pd3/markupsafe/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --egg-base /tmp/pip-pip-egg-info-bk6ldht4', '         cwd: /tmp/pip-install-5kl59pd3/markupsafe/', '    Complete output (5 lines):', '    Traceback (most recent call last):', '      File "<string>", line 1, in <module>', '      File "/tmp/pip-install-5kl59pd3/markupsafe/setup.py", line 6, in <module>', '        from setuptools import setup, Extension, Feature', "    ImportError: cannot import name 'Feature' from 'setuptools' (/home/alpha/.local/share/virtualenvs/superbook2-HNnQDu9M/lib/python3.8/site-packages/setuptools/__init__.py)", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.']
ERROR: ERROR: Package installation failed...
```

So on a newly installed Fedora 32 machine, I did only:

$ sudo dnf install git
$ sudo dnf install pipenv
$ git clone https://github.com/DjangoPatternsBook/superbook2.git
$ cd superbook2
$ pipenv install --dev

and I think this same (or similar) sequence of commands will fail similarly in other python environments.
`$ pipenv --support` output attached as a file.
[pipenv__support_fedora32.txt](https://github.com/DjangoPatternsBook/superbook2/files/5091308/pipenv__support_fedora32.txt)

**Comment by dingouerinitx** [comment]
In case someone is still struggling with this issue, I was not able to solve it entirely and in a correct way (would love to hear a solution which updates the pipfile accordingly), but to bring the app up running. 

The workaround is simple as that:

1. Install as described above or in the book
2. Ignore the error from `markupsafe`
3. Enter the virtualenv with `pipenv shell`
4. Install markupsafe with `pip install markupsafe` which will install latest version 1.1.1 correctly
5. then make your pre-preparations for running the app described below

```bash
cd src
python manage.py migrate
python manage.py createsuperuser
python manage.py run
```

**As a note:** `pipenv graph` showed that markupsafe 1.1.1 has been installed, but `pip freeze` shows contradictory information, so that lead me to the assumption to just install it again with `pip install markupsafe` and it did.

```bash
#>pipenv graph
coreapi==2.3.3
  - coreschema [required: Any, installed: 0.0.4]
    - jinja2 [required: Any, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
  - itypes [required: Any, installed: 1.1.0]
  - requests [required: Any, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2018.4.16]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: >=1.21.1,<1.23, installed: 1.22]
  - uritemplate [required: Any, installed: 3.0.0]
django-authtools==1.6.0
  - Django [required: >=1.8, installed: 2.0]
    - pytz [required: Any, installed: 2018.4]
django-braces==1.12.0
django-crispy-forms==1.7.2
django-debug-toolbar==1.8
  - Django [required: >=1.8, installed: 2.0]
    - pytz [required: Any, installed: 2018.4]
  - sqlparse [required: >=0.2.0, installed: 0.2.4]
django-environ==0.4.4
  - django [required: Any, installed: 2.0]
    - pytz [required: Any, installed: 2018.4]
  - six [required: Any, installed: 1.11.0]
django-extensions==2.0.7
  - six [required: >=1.2, installed: 1.11.0]
django-heroku==0.3.1
  - dj-database-url [required: >=0.5.0, installed: 0.5.0]
  - django [required: Any, installed: 2.0]
    - pytz [required: Any, installed: 2018.4]
  - psycopg2 [required: Any, installed: ?]
  - whitenoise [required: Any, installed: 3.3.1]
django-widget-tweaks==1.4.1
djangorestframework==3.8.2
gunicorn==19.8.1
pudb==2018.1
  - pygments [required: >=1.0, installed: 2.2.0]
  - urwid [required: >=1.1.1, installed: 2.0.1]
pytest==3.6.1
  - atomicwrites [required: >=1.0, installed: 1.1.5]
  - attrs [required: >=17.4.0, installed: 18.1.0]
  - more-itertools [required: >=4.0.0, installed: 4.2.0]
    - six [required: >=1.0.0,<2.0.0, installed: 1.11.0]
  - pluggy [required: >=0.5,<0.7, installed: 0.6.0]
  - py [required: >=1.5.0, installed: 1.5.3]
  - setuptools [required: Any, installed: 49.6.0]
  - six [required: >=1.10.0, installed: 1.11.0]
python-decouple==3.1
```

```bash
#>pip freeze
atomicwrites==1.1.5
attrs==18.1.0
certifi==2018.4.16
chardet==3.0.4
coreapi==2.3.3
coreschema==0.0.4
dj-database-url==0.5.0
Django==2.0
django-authtools==1.6.0
django-braces==1.12.0
django-crispy-forms==1.7.2
django-debug-toolbar==1.8
django-environ==0.4.4
django-extensions==2.0.7
django-heroku==0.3.1
django-widget-tweaks==1.4.1
djangorestframework==3.8.2
gunicorn==19.8.1
idna==2.6
itypes==1.1.0
Jinja2==2.10
more-itertools==4.2.0
pluggy==0.6.0
pudb==2018.1
py==1.5.3
Pygments==2.2.0
pytest==3.6.1
python-decouple==3.1
pytz==2018.4
requests==2.18.4
six==1.11.0
sqlparse==0.2.4
uritemplate==3.0.0
urllib3==1.22
urwid==2.0.1
whitenoise==3.3.1
```

```bash
#>pip install markupsafe
Collecting markupsafe
  Using cached MarkupSafe-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl (16 kB)
Installing collected packages: markupsafe
Successfully installed markupsafe-1.1.1
```

```bash
#>pip freeze
atomicwrites==1.1.5
attrs==18.1.0
certifi==2018.4.16
chardet==3.0.4
coreapi==2.3.3
coreschema==0.0.4
dj-database-url==0.5.0
Django==2.0
django-authtools==1.6.0
django-braces==1.12.0
django-crispy-forms==1.7.2
django-debug-toolbar==1.8
django-environ==0.4.4
django-extensions==2.0.7
django-heroku==0.3.1
django-widget-tweaks==1.4.1
djangorestframework==3.8.2
gunicorn==19.8.1
idna==2.6
itypes==1.1.0
Jinja2==2.10
MarkupSafe==1.1.1
more-itertools==4.2.0
pluggy==0.6.0
pudb==2018.1
py==1.5.3
Pygments==2.2.0
pytest==3.6.1
python-decouple==3.1
pytz==2018.4
requests==2.18.4
six==1.11.0
sqlparse==0.2.4
uritemplate==3.0.0
urllib3==1.22
urwid==2.0.1
whitenoise==3.3.1
```
I used latest python version **3.8.5**. Hope that helps.
